language: csharp
dist: bionic
mono: none
dotnet: 3.1.403
git:
  depth: false
branches:
  only:
    - master
    - dev
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
  - ./scripts/travis-test.sh
after_success:
  - ./scripts/travis-success.sh
notifications:
  email:
    recipients:
      - seoquesto@gmail.com
    on_success: never
    on_failure: always