version: '2'

services:
  # api:
  #   build: ../src/DriverRatings.Api
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - database
  database:
    image: mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ../temp/mongo-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017

volumes:
  db-data: