version: '2'

services:
  # api:
  #   container_name: api
  #   image: seoquesto/driver-ratings:dev
  #   ports:
  #     - '5000:5000'
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    env_file:
        - .env
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    ports:
      - 27017:27017
    command: ["-f", "/etc/mongod.conf"]